apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-container-node
          image: dani03/kub-app:1.0.0